name: CI

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
    - master

jobs:
  python-ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    name: CI workflow
    steps:
      - name: checkout source repo
        uses: actions/checkout@v2      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Installs dependencies"
        run: |
          # Upgrade pip
          python3 -m pip install --upgrade pip
          # Install build deps
          pip install setuptools pytest flake8 ipython
          # Install the package from setup.py
          pip install .
      - name: linting flake8
        run: |
          flake8
      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: ${{ matrix.os }},${{ matrix.python-version }}
          fail_ci_if_error: true
          flags: pytest
          name: codecov-umbrella
          verbose: true